name: TuCheTao
version: '$version'
main: org.simpmc.autocraft.ACPlugin
api-version: '1.16'
description: "Plugin TuCheTao"
website: "https://simpmc.net"
authors:
  - typical.smc
  - Cortez_Romeo
softdepend:
  - MMOItems
  - ItemsAdder
permissions:
  tuchetao.use:
    default: true
    description: Allow player to use /tuchetao command
  tuchetao.admin.reload:
    default: op
  tuchetao.xemcongthuc:
    default: true
    description: Allow player to use /xemcongthuc command